version: '3.3'
services:
  website:
    image: node:16
    user: ${RUNAS}
    volumes:
      - ${VAR_ROOT}/shared:/tmp/shared
      - ${VAR_ROOT}/home:/tmp/home
      - ../:/tmp/src
    working_dir: /tmp/src/website
    environment:
      HOME: /tmp/home
      DB_URL: ${DB_URL}
      NODE_ENV: ${NODE_ENV}
    command: npm start
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.4
    user: ${RUNAS}
    volumes:
      - ${VAR_ROOT}/shared:/tmp/shared
      - ${VAR_ROOT}/mongo:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    ports:
      - "0.0.0.0:8081:8081"
    depends_on:
      - mongo
